spring:
  application:
    name: msvc-api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

# Configuraci√≥n del cliente gRPC
grpc:
  client:
    autenticacion-service:
      address: static://localhost:9091
      negotiationType: plaintext

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.cors: TRACE
    org.springframework.web.reactive: TRACE
    reactor.netty.http.server: DEBUG
